---
name: TacoBot Beta Publish
on:
  push:
    branches:
      - '!develop'
      - '!main'
      - "!master"
env:
  GITHUB_TOKEN: "${{ github.token }}"
  IMAGE_ORG: "${{ github.repository_owner }}"
  IMAGE_NAME: "${{ github.event.repository.name }}"
  GH_IMAGE_REGISTRY: "ghcr.io"
  BUILD_TAGS: ""
  BUILD_DATE: ""
  PROJECT_NAME: "${{ github.event.repository.name }}"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare
        id: prep
        run: |
          # lower case the container org
          IMAGE_ORG="${IMAGE_ORG,,}";
          # lower case the container name
          IMAGE_NAME="${IMAGE_NAME,,}";
          GHCR_IMAGE="${GH_IMAGE_REGISTRY}/${IMAGE_ORG}/${IMAGE_NAME}";

          TAGSZ="${GHCR_IMAGE}:beta,${GHCR_IMAGE}:beta-${{ github.sha }}";
          BUILD_DATEZ="$(date +'%Y-%m-%dT%TZ%z' -u)";
          PROJECT_NAMEZ="${IMAGE_NAME}";
          echo "BUILD_TAGS=${TAGSZ}" >> "$GITHUB_ENV";
          echo "BUILD_DATE=${BUILD_DATEZ}" >> "$GITHUB_ENV";
          echo "PROJECT_NAME=${PROJECT_NAMEZ}" >> "$GITHUB_ENV";

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: "${{ env.GH_IMAGE_REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ github.token }}"

      - name: Build and Push GHCR
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          provenance: false
          build-args: |
            PROJECT_NAME=${{ env.PROJECT_NAME }}
            BUILD_VERSION=beta-${{ github.sha }}
          tags: "${{ env.BUILD_TAGS }}"
