name: TacoBot Publish
on:
  push:
    branches:
      - develop
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: lowercase repo name
      run: |
        echo "REPOSITORY_NAME=$(echo "${{ github.repository }}" | awk '{print tolower($0)}')" >> $GITHUB_ENV

    - name: Prepare
      id: prep
      run: |
        GHCR_IMAGE="ghcr.io/${{ env.REPOSITORY_NAME }}";

        TAGSZ="${GHCR_IMAGE}:beta,${GHCR_IMAGE}:beta-${{ github.sha }}";
        BUILD_DATEZ="$(date +'%Y-%m-%dT%TZ%z' -u)";
        PROJECT_NAMEZ=`echo "${{ env.REPOSITORY_NAME }}" | awk '{split($0,a,"/"); print a[2]}'`;
        echo BUILD_TAGS=${TAGSZ} >> $GITHUB_ENV;
        echo BUILD_DATE=${BUILD_DATEZ} >> $GITHUB_ENV;
        echo PROJECT_NAME=${PROJECT_NAMEZ} >> $GITHUB_ENV;

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build and Push GHCR
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        push: true
        build-args: |
          PROJECT_NAME=${{ env.PROJECT_NAME }}
          BUILD_VERSION=${{ needs.version.outputs.app_version }}
        tags: ${{ env.BUILD_TAGS }}
